In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [4]:
#location
#Price per area
#rental Yeild
def scrap_housingcom(filename):
    headers={"User-Agent": "Mozilla/5.0 (X11; CrOS x86_64 12871.102.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.141 Safari/537.36"}
    wp=requests.get('https://housing.com/rent/search-Psrbcrw7p4zhuczr',headers=headers).text
    
    html=BeautifulSoup(wp,'lxml')
    
    Rental_Yeild=[]
    Location=[]
    Price=[]
    for i in html.find_all('div',class_='T_091c165f _sq1l2s _vv1q9c _ks15vq T_3d3547ab _7s5wglyw _5vy24jg8 _blas1v10 new-title'):
        x=i.text.strip()
        temp=x.split(' ')[0]+' '+x.split(' ')[1]
        Rental_Yeild.append(temp)
    
    for i in html.find_all('div',class_='T_091c165f _sq1l2s _vv1q9c _ks15vq T_3d3547ab _7s5wglyw _5vy24jg8 _blas1v10 new-title'):
        x=i.text.strip()
        text=x.split()
        index=text.index('in')
        try:
            temp=x.split(' ')[index+1]+' '+x.split(' ')[index+2]
            Location.append(temp)
        except:
            temp=x.split(' ')[index+1]
            Location.append(temp)
    
    for i in html.find_all('div',class_="_csbfng _c8exct _g3qslr _fr1nms _1q73f6fq _4okugktf _1qkcc65e _j3gpidpf _4nrxyh40 T_a6707275"):
        Price.append(i.text.strip())
    
    df_SrapData = pd.DataFrame({
    'Location': Location,
    'Rental_Yeild': Rental_Yeild,
    'Price': Price
    })
    df_SrapData.to_csv(filename)
    return df_SrapData

In [5]:
scrap_housingcom('demo.csv')

         Location Rental_Yeild      Price
0   Banjara Hills        3 BHK  ₹1,25,001
1   Banjara Hills        3 BHK    ₹65,000
2      Gachibowli        1 BHK    ₹29,000
3      Gachibowli        1 BHK    ₹25,000
4         Kokapet        3 BHK    ₹65,000
5        Kondapur        2 BHK    ₹35,000
6        Kondapur        1 BHK    ₹23,000
7        Kondapur        1 BHK    ₹26,000
8       Manikonda        1 BHK    ₹12,000
9         Nagaram        2 BHK    ₹10,000
10     Kukatpally        3 BHK    ₹60,000
11       Kondapur        2 BHK    ₹30,000
12       Kondapur        1 BHK    ₹20,000
13       Kondapur        1 BHK    ₹23,000
14       Kondapur        1 BHK    ₹25,000
15   Ibrahim Bagh        4 BHK  ₹1,80,000
16      Kothaguda        3 BHK    ₹85,000
17         Mokila        3 BHK    ₹75,000
18       Kondapur        2 BHK    ₹20,111
19     Kondapur -        1 BHK    ₹15,000
20       Kondapur        3 BHK    ₹35,001
21     Somajiguda        3 BHK    ₹70,000
22       Kondapur        1 BHK    ₹17,500
23       Kondapur        2 BHK    ₹30,000
24       Kondapur        4 BHK  ₹1,00,000
25    Peeramcheru        4 BHK    ₹90,000
26    Maheshwaram        1 BHK    ₹45,000
27       Kondapur        1 BHK    ₹15,502
28       Kondapur        1 BHK    ₹20,000
29     Gachibowli        2 BHK    ₹33,000